name: "Facebook Behavior: Page Videos (Owner Logged In)"

on:
  push:
  pull_request:
  schedule:
    - cron: '33 16 * * *'

jobs:
  facebook_test:
    environment: DigitalOcean
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: prewk/s3-cp-action@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        SOURCE: ${{ secrets.PROFILE_URL }}
        DEST: './profile.tar.gz'

    - name: install requirements
      run: yarn install

    - uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: test/test.env

    - name: get browsertrix image
      run:  docker pull $BROWSERTRIX_IMAGE

    - name: run crawl
      run: docker run -v $PWD/dist/behaviors.js:/app/node_modules/browsertrix-behaviors/dist/behaviors.js -v $PWD/profile.tar.gz:/profile.tar.gz $BROWSERTRIX_IMAGE crawl --url https://www.facebook.com/Capture-Sample-105559135004406/videos --limit 1 --logging behaviors --profile /profile.tar.gz > ./log

    - name: cat log
      run: cat ./log

    - name: compare crawl log to expected
      run: grep '"state"' ./log | diff - ./test/expected-facebook-videos.log

