name: Lint Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install requirements
      run: yarn install
    - name: run linter
      run: yarn run eslint index.ts src/**/*.ts
    - name: Bulid
      run: yarn build
  
       
